# Generated by Django 3.1.4 on 2021-01-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSE_eve_batch_info',
            fields=[
                ('dept', models.CharField(max_length=5)),
                ('batch_no', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('st_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CSE_eve_trimister',
            fields=[
                ('trimister', models.IntegerField(primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_eve_batch_info')),
            ],
        ),
        migrations.CreateModel(
            name='CSE_eve_course_list',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_eve_trimister')),
            ],
        ),
    ]
