# Generated by Django 3.1.4 on 2021-01-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVE_routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('st_number', models.IntegerField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
