# Generated by Django 3.1.4 on 2021-01-25 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_eve_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEN_eve_batch_info',
            fields=[
                ('dept', models.CharField(max_length=5)),
                ('batch_no', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('st_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EEE_eve_batch_info',
            fields=[
                ('dept', models.CharField(max_length=5)),
                ('batch_no', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10)),
                ('st_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EEE_eve_trimister',
            fields=[
                ('trimister', models.IntegerField(primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_eve_batch_info')),
            ],
        ),
        migrations.CreateModel(
            name='EEE_eve_course_list',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_eve_trimister')),
            ],
        ),
        migrations.CreateModel(
            name='CEN_eve_trimister',
            fields=[
                ('trimister', models.IntegerField(primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_eve_batch_info')),
            ],
        ),
        migrations.CreateModel(
            name='CEN_eve_course_list',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_eve_trimister')),
            ],
        ),
    ]
