# Generated by Django 3.1.4 on 2021-01-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_cen_eve_batch_info_cen_eve_course_list_cen_eve_trimister_eee_eve_batch_info_eee_eve_course_list_eee_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cen_eve_course_list',
            name='trimister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cen_eve_trimister'),
        ),
        migrations.AlterField(
            model_name='cen_eve_trimister',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cen_eve_batch_info'),
        ),
        migrations.AlterField(
            model_name='eee_eve_course_list',
            name='trimister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.eee_eve_trimister'),
        ),
        migrations.AlterField(
            model_name='eee_eve_trimister',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.eee_eve_batch_info'),
        ),
    ]
