# Generated by Django 3.1.4 on 2021-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20210125_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eve_routine',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
