# Generated by Django 3.1.4 on 2021-01-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20210126_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cse_eve_trimister',
            name='batch',
        ),
    ]
