# Generated by Django 3.1.4 on 2021-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_cse_eve_batch_info_trimister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cse_eve_batch_info',
            name='batch_no',
            field=models.IntegerField(),
        ),
    ]
