# Generated by Django 3.1.4 on 2021-01-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20210126_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSE_eve_batch_info',
        ),
    ]
