# Generated by Django 3.1.4 on 2021-01-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_delete_cse_eve_batch_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSE_eve_batch_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('st_number', models.IntegerField()),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_eve_trimister')),
            ],
        ),
    ]
