# Generated by Django 3.1.4 on 2021-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_cse_eve_batch_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cse_eve_trimister',
            name='dept',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
