# Generated by Django 3.1.4 on 2021-01-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_cse_eve_trimister_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cse_eve_batch_info',
            name='trimister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.cse_eve_trimister'),
        ),
    ]
