# Generated by Django 3.1.4 on 2021-01-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20210126_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cen_eve_trimister',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='eee_eve_trimister',
            name='batch',
        ),
    ]
