# Generated by Django 3.1.4 on 2021-01-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20210126_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cen_eve_trimister',
            name='dept',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='eee_eve_trimister',
            name='dept',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='EEE_eve_batch_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('st_number', models.IntegerField()),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.eee_eve_trimister')),
            ],
        ),
        migrations.CreateModel(
            name='CEN_eve_batch_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('st_number', models.IntegerField()),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cen_eve_trimister')),
            ],
        ),
    ]
