# Generated by Django 3.1.4 on 2021-01-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20210126_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eve_routine',
            old_name='program',
            new_name='dept',
        ),
    ]
