# Generated by Django 3.1.4 on 2021-01-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20210127_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cse_eve_course_list',
            name='trimister',
        ),
        migrations.DeleteModel(
            name='CEN_eve_course_list',
        ),
        migrations.DeleteModel(
            name='CSE_eve_course_list',
        ),
    ]
