# Generated by Django 3.1.4 on 2021-01-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_auto_20210127_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EEE_eve_course_list',
        ),
    ]
