# Generated by Django 3.1.4 on 2021-01-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_eve_exam_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVE_exam_date_time',
        ),
    ]
