# Generated by Django 3.1.4 on 2021-01-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_delete_eve_exam_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVE_exam_date_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True)),
                ('exam_time', models.CharField(blank=True, max_length=15, null=True)),
                ('start_with', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
