# Generated by Django 3.1.4 on 2021-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_eve_exam_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eve_routine',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eve_routine',
            name='exam_time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
