# Generated by Django 3.1.4 on 2021-01-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_auto_20210129_0102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVE_exam_date_time',
        ),
    ]
