# Generated by Django 3.1.4 on 2021-01-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_eve_routine_total_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='eve_routine',
            name='weekday',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
