# Generated by Django 3.1.4 on 2021-01-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_bte_eve_batch_info_bte_eve_course_list_bte_eve_trimister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bte_eve_batch_info',
            name='trimister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.bte_eve_trimister'),
        ),
    ]
