# Generated by Django 3.1.4 on 2021-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_auto_20210131_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bte_eve_trimister',
            name='trimister',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
