# Generated by Django 3.1.4 on 2021-01-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0031_auto_20210131_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSE_day_trimister',
            fields=[
                ('dept', models.CharField(blank=True, max_length=5, null=True)),
                ('trimister', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CSE_day_course_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_day_trimister')),
            ],
        ),
        migrations.CreateModel(
            name='CSE_day_batch_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('st_number', models.IntegerField()),
                ('trimister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.cse_day_trimister')),
            ],
        ),
    ]
