# Generated by Django 3.1.4 on 2021-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0033_bte_day_batch_info_bte_day_course_list_bte_day_trimister_cen_day_batch_info_cen_day_course_list_cen_'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAY_routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('total_st', models.IntegerField(blank=True, null=True)),
                ('st_number', models.IntegerField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_time', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
