# Generated by Django 3.1.4 on 2021-02-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0034_day_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eve_routine',
            name='day',
        ),
    ]
