# Generated by Django 3.1.4 on 2021-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0035_remove_eve_routine_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('teimister', models.CharField(blank=True, max_length=10, null=True)),
                ('term', models.CharField(blank=True, max_length=10, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('pub_state', models.BooleanField(default=False)),
            ],
        ),
    ]
