# Generated by Django 3.1.4 on 2021-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0036_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='id',
        ),
        migrations.AlterField(
            model_name='publish',
            name='batch',
            field=models.CharField(blank=True, default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
