# Generated by Django 3.1.4 on 2021-02-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0037_auto_20210203_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='pub_state',
        ),
    ]
