# Generated by Django 3.1.4 on 2021-02-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0038_remove_publish_pub_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='teimister',
            new_name='trimister',
        ),
    ]
